stages:
  - test
  - deploy

test:
  stage: test
  script:
    - npm install
    - npm run lint
  cache:
    key: $CI_COMMIT_REF_NAME
    paths:
      - node_modules
  tags:
    - echo-linux

publish:
  stage: deploy
  tags:
    - echo-linux
  only:
    - tags
  script:
    - npm install
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm publish
    - rm .npmrc
