language: node_js
node_js:
  - "10"


stages:
  - audit
  - test
  - deploy


jobs:
  include:
    - stage: audit
      if: tag IS blank
      name: "Test lint and audit"
      script:
        - npm run lint
        - audit-ci --moderate
    - stage: test
      if: type = pull_request
      name: "Run unit testing"
      services:
        - docker
      before_install:
        - docker pull echoprotocol/echo:v0.8.2
        - docker pull echoprotocol/echo-wallet:v0.9.0-rc.1
        - docker-compose -f ./.test/docker-compose.yml up
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm test; fi'
    - stage: deploy
      if: tag IS present
      name: "Deploy to npm"
      script:
        - npm install
        - npm run build
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
