language: node_js
node_js:
  - "10"


stages:
  - audit
  - test
  - deploy


jobs:
  include:
    - stage: audit
#      if: tag IS blank
      if: branch = master
      name: "Test lint and audit"
      script:
        - npm run lint
        - audit-ci --moderate
    - stage: test
      if: branch = master
      name: "Run unit testing"
      services:
        - docker
      before_install:
        - docker pull echoprotocol/echo:v0.8.2
        - docker run --name echotest -p 6311:6311 -v $PWD/.test/genesis_devnet.json:/echo/genesis_devnet.json -v $PWD/.test/access.json:/echo/access.json -d echoprotocol/echo:v0.8.3 --devnet --start-echorand --account-info="[\"1.2.6\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]" --account-info="[\"1.2.7\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]" --account-info="[\"1.2.8\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]" --account-info="[\"1.2.9\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]" --account-info="[\"1.2.10\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]" --rpc-endpoint=0.0.0.0:6311 --plugins=registration --api-access=/echo/access.json
      script:
        - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then npm test; fi'
    - stage: deploy
#      if: tag IS present
      name: "Deploy to npm"
      script: "echo \"Deploy\""
      deploy:
        provider: npm
        script:
          - npm i
          - npm run prepare
        email: $NPM_EMAIL
        on:
          all_branches: true
        api_key: $NPM_TOKEN
#        on:
#          tags: true
