import ObjectIdSerializer from "./ObjectId";
import { RESERVED_SPACE_ID } from "../../../constants/chain-types";

export declare const accountId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const assetId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const committeeMemberId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const proposalId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const vestingBalanceId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const balanceId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const contractId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const ethDepositId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const withdrawId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const erc20TokenId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const depositErc20TokenId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const withdrawErc20TokenId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const btcAddressId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const btcIntermediateDepositId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const btcDepositId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export declare const btcWithdrawId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
export const btcAggregatingId: ObjectIdSerializer<RESERVED_SPACE_ID.PROTOCOL>;
