version: "2"

services:
  echo:
    image: echoprotocol/echo:v0.8.2
    command:  --devnet --start-echorand
      --account-info="[\"1.2.6\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.7\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.8\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.9\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.10\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --rpc-endpoint=0.0.0.0:6311 --plugins=registration --api-access=/echo/access.json
    ports:
      - 6311:6311
    volumes:
      - ./genesis_devnet.json:/echo/genesis_devnet.json
      - ./access.json:/echo/access.json
  echo-wallet:
    image: echoprotocol/echo-wallet:v0.9.0-rc.1
    command:  -s ws://192.168.1.93:6311/ws
      --chain-id="e0b8b3f26b0107d5f1f5060266c9112554234036bb3b239afba3d258c6409196"
      --wallet-file="/echo/walletdata/wallet.json"
      --history-file="/echo/walletdata/history"
      --rpc-endpoint=0.0.0.0:8888
    ports:
      - 8888:8888
    links:
      - echo
