version: "2"

services:
  echo:
    image: echoprotocol/echo:0.22-rc.1
    command:
      --start-echorand
      --account-info="[\"1.2.6\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.7\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.8\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.9\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.10\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --registrar-account=\"1.2.10\"
      --rpc-endpoint=0.0.0.0:6311
      --plugins=registration
      --api-access=/echo/access.json
      --genesis-json=genesis.json
      -d datadir
    ports:
      - 6311:6311
    volumes:
      - ./genesis.json:/echo/genesis.json
      - ./access.json:/echo/access.json
    container_name: echo

  echo-wallet:
    image: echoprotocol/echo-wallet:0.22-rc.1
    container_name: echo-wallet
    command:
      -s ws://echo:6311
      --chain-id="acd81c215a20e2b3281195362146215c82874d52783fbb4cb35924edd99c716c"
      --wallet-file="/echo/walletdata/wallet.json"
      --history-file="/echo/walletdata/history"
      -r 0.0.0.0:6312
    ports:
      - 6312:6312
    tty: true
    links:
      - echo
