version: "2"

services:
  echo:
    image: echoprotocol/echo:0.11.0-rc.1
    command:
      --start-echorand
      --account-info="[\"1.2.6\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.7\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.8\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.9\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --account-info="[\"1.2.10\", \"5KkYp8qdQBaRmLqLz8WVrGjzkt7E13qVcr7cpdLowgJ1mjRyDx2\"]"
      --rpc-endpoint=0.0.0.0:6311
      --plugins=registration
      --api-access=/echo/access.json
      --genesis-json=genesis.json
      -d datadir
    ports:
      - 6311:6311
    volumes:
      - ./genesis.json:/echo/genesis.json
      - ./access.json:/echo/access.json
    container_name: echo

  echo-wallet:
    image: echoprotocol/echo-wallet:0.11.0-rc.1
    container_name: echo-wallet
    command:
      -s wss://devnet.echo-dev.io/ws
      --chain-id="1e68eb8828bd9053e14c9ee2ba89b0403be8e92be181782f797dd64c1b68dec6"
      --wallet-file="/echo/walletdata/wallet.json"
      --history-file="/echo/walletdata/history"
      -r 0.0.0.0:6312
    ports:
      - 6312:6312
    tty: true
    links:
      - echo
