const ChainTypes = {};

ChainTypes.reserved_spaces = {
	relative_protocol_ids: 0,
	protocol_ids: 1,
	implementation_ids: 2,
};

ChainTypes.object_type = {
	null: 0,
	base: 1,
	account: 2,
	asset: 3,
	force_settlement: 4,
	committee_member: 5,
	limit_order: 6,
	call_order: 7,
	custom: 8,
	proposal: 9,
	operation_history: 10,
	withdraw_permission: 11,
	vesting_balance: 12,
	balance: 13,
	contract: 14,
	contract_result: 15,
	block_result: 16,
	eth_address: 17,
	deposit_eth: 18,
	withdraw_eth: 19,
	OBJECT_TYPE_COUNT: 20
};

ChainTypes.impl_object_type = {
	global_property: 0,
	dynamic_global_property: 1,
	asset_dynamic_data: 2,
	asset_bitasset_data: 3,
	account_balance: 4,
	account_statistics: 5,
	transaction: 6,
	block_summary: 7,
	account_transaction_history: 8,
	chain_property: 9,
	budget_record: 10,
	special_authority: 11,
	buyback: 12,
	collateral_bid: 13,
	contract_balance: 14,
	contract_history: 15,
	contract_statistics: 16,
	account_address: 17,
	contract_pool: 18
};

ChainTypes.vote_type = {
	committee: 0,
};

ChainTypes.operations = {
	transfer: 0,
	limit_order_create: 1,
	limit_order_cancel: 2,
	call_order_update: 3,
	fill_order: 4,
	account_create: 5,
	account_update: 6,
	account_whitelist: 7,
	account_upgrade: 8,
	account_transfer: 9,
	asset_create: 10,
	asset_update: 11,
	asset_update_bitasset: 12,
	asset_update_feed_producers: 13,
	asset_issue: 14,
	asset_reserve: 15,
	asset_fund_fee_pool: 16,
	asset_settle: 17,
	asset_global_settle: 18,
	asset_publish_feed: 19,
	proposal_create: 20,
	proposal_update: 21,
	proposal_delete: 22,
	withdraw_permission_create: 23,
	withdraw_permission_update: 24,
	withdraw_permission_claim: 25,
	withdraw_permission_delete: 26,
	committee_member_create: 27,
	committee_member_update: 28,
	committee_member_update_global_parameters: 29,
	vesting_balance_create: 30,
	vesting_balance_withdraw: 31,
	custom: 32,
	assert: 33,
	balance_claim: 34,
	override_transfer: 35,
	asset_settle_cancel: 36,
	asset_claim_fees: 37,
	bid_collateral: 38,
	execute_bid: 39,
	create_contract: 40,
	call_contract: 41,
	contract_transfer: 42,
	change_sidechain_config: 43,
	account_address_create: 44,
	transfer_to_address: 45,
	generate_eth_address: 46,
	create_eth_address: 47,
	deposit_eth: 48,
	withdraw_eth: 49,
	approve_withdraw_eth: 50,
	contract_fund_pool: 51,
	contract_whitelist: 52,
	sidechain_issue: 53,
	sidechain_burn: 54
};

module.exports = ChainTypes;
