export const LOOKUP_ACCOUNTS_DEFAULT_LIMIT = 100;
export const LOOKUP_ACCOUNTS_MAX_LIMIT = 1000;

export const LIST_ASSETS_DEFAULT_LIMIT = 10;
export const LIST_ASSETS_MAX_LIMIT = 100;

export const GET_TRADE_HISTORY_DEFAULT_LIMIT = 10;
export const GET_TRADE_HISTORY_MAX_LIMIT = 100;

export const LOOKUP_WITNESS_ACCOUNTS_DEFAULT_LIMIT = 100;
export const LOOKUP_WITNESS_ACCOUNTS_MAX_LIMIT = 1000;

export const COMMITTEE_MEMBER_ACCOUNTS_DEFAULT_LIMIT = 100;
export const COMMITTEE_MEMBER_ACCOUNTS_MAX_LIMIT = 1000;

export const ACCOUNT_HISTORY_DEFAULT_LIMIT = 100;
export const ACCOUNT_HISTORY_MAX_LIMIT = 100;

export const RELATIVE_ACCOUNT_HISTORY_DEFAULT_LIMIT = 100;
export const RELATIVE_ACCOUNT_HISTORY_MAX_LIMIT = 100;

export const RELATIVE_ACCOUNT_HISTORY_START = 0;
export const RELATIVE_ACCOUNT_HISTORY_STOP = 0;

export const ACCOUNT_HISTORY_OPERATIONS_DEFAULT_LIMIT = 100;
export const ACCOUNT_HISTORY_OPERATIONS_MAX_LIMIT = 100;

export const CONTRACT_HISTORY_DEFAULT_LIMIT = 100;
export const CONTRACT_HISTORY_MAX_LIMIT = 100;

export const START_OPERATION_HISTORY_ID = '1.11.0';
export const STOP_OPERATION_HISTORY_ID = '1.11.0';
