import * as props from "./props";
import { StaticVariantSerializer } from "../collections";
import OperationId from "../../interfaces/OperationId";
import ISerializer from "../ISerializer";

export type OperationPropsSerializer<T extends OperationId> = {
	[OperationId.TRANSFER]: typeof props.transfer,
	[OperationId.LIMIT_ORDER_CREATE]: ISerializer,
	[OperationId.LIMIT_ORDER_CANCEL]: ISerializer,
	[OperationId.CALL_ORDER_UPDATE]: ISerializer,
	[OperationId.FILL_ORDER]: ISerializer,
	[OperationId.ACCOUNT_CREATE]: ISerializer,
	[OperationId.ACCOUNT_UPDATE]: ISerializer,
	[OperationId.ACCOUNT_WHITELIST]: ISerializer,
	[OperationId.ACCOUNT_UPGRADE]: ISerializer,
	[OperationId.ACCOUNT_TRANSFER]: ISerializer,
	[OperationId.ASSET_CREATE]: ISerializer,
	[OperationId.ASSET_UPDATE]: ISerializer,
	[OperationId.ASSET_UPDATE_BITASSET]: ISerializer,
	[OperationId.ASSET_UPDATE_FEED_PRODUCERS]: ISerializer,
	[OperationId.ASSET_ISSUE]: ISerializer,
	[OperationId.ASSET_RESERVE]: ISerializer,
	[OperationId.ASSET_FUND_FEE_POOL]: ISerializer,
	[OperationId.ASSET_SETTLE]: ISerializer,
	[OperationId.ASSET_GLOBAL_SETTLE]: ISerializer,
	[OperationId.ASSET_PUBLISH_FEED]: ISerializer,
	[OperationId.PROPOSAL_CREATE]: ISerializer,
	[OperationId.PROPOSAL_UPDATE]: ISerializer,
	[OperationId.PROPOSAL_DELETE]: ISerializer,
	[OperationId.WITHDRAW_PERMISSION_CREATE]: ISerializer,
	[OperationId.WITHDRAW_PERMISSION_UPDATE]: ISerializer,
	[OperationId.WITHDRAW_PERMISSION_CLAIM]: ISerializer,
	[OperationId.WITHDRAW_PERMISSION_DELETE]: ISerializer,
	[OperationId.COMMITTEE_MEMBER_CREATE]: ISerializer,
	[OperationId.COMMITTEE_MEMBER_UPDATE]: ISerializer,
	[OperationId.COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS]: ISerializer,
	[OperationId.VESTING_BALANCE_CREATE]: ISerializer,
	[OperationId.VESTING_BALANCE_WITHDRAW]: ISerializer,
	[OperationId.CUSTOM]: ISerializer,
	[OperationId.ASSERT]: ISerializer,
	[OperationId.BALANCE_CLAIM]: ISerializer,
	[OperationId.OVERRIDE_TRANSFER]: ISerializer,
	[OperationId.ASSET_SETTLE_CANCEL]: ISerializer,
	[OperationId.ASSET_CLAIM_FEES]: ISerializer,
	[OperationId.BID_COLLATERAL]: ISerializer,
	[OperationId.EXECUTE_BID]: ISerializer,
	[OperationId.CREATE_CONTRACT]: ISerializer,
	[OperationId.CALL_CONTRACT]: ISerializer,
	[OperationId.CONTRACT_TRANSFER]: ISerializer,
	[OperationId.CHANGE_SIDECHAIN_CONFIG]: ISerializer,
	[OperationId.ACCOUNT_ADDRESS_CREATE]: ISerializer,
	[OperationId.TRANSFER_TO_ADDRESS]: ISerializer,
	[OperationId.GENERATE_ETH_ADDRESS]: ISerializer,
	[OperationId.CREATE_ETH_ADDRESS]: ISerializer,
	[OperationId.DEPOSIT_ETH]: ISerializer,
	[OperationId.WITHDRAW_ETH]: ISerializer,
	[OperationId.APPROVE_WITHDRAW_ETH]: ISerializer,
	[OperationId.CONTRACT_FUND_POOL]: ISerializer,
	[OperationId.CONTRACT_WHITELIST]: ISerializer,
	[OperationId.SIDECHAIN_ISSUE]: ISerializer,
	[OperationId.SIDECHAIN_BURN]: ISerializer,
	[OperationId.REGISTER_ERC20_TOKEN]: ISerializer,
	[OperationId.DEPOSIT_ERC20_TOKEN]: ISerializer,
	[OperationId.WITHDRAW_ERC20_TOKEN]: ISerializer,
	[OperationId.APPROVE_ERC20_TOKEN_WITHDRAW]: ISerializer,
	[OperationId.CONTRACT_UPDATE]: ISerializer,
}[T];

declare const operationSerilizer: StaticVariantSerializer<{
	[operationId in OperationId]: OperationPropsSerializer<operationId>
}>;

export default operationSerilizer;
