import { transfer as transferOpProps, account, asset, proposal, committeeMember, vesting, balance } from '../protocol';

export declare const transfer: typeof transferOpProps;
export declare const accountCreate: typeof account.create;
export declare const accountUpdate: typeof account.update;
export declare const accountWhitelist: typeof account.whitelist;
export declare const accountTransfer: typeof account.transfer;
export declare const assetCreate: typeof asset.create;
export declare const assetUpdate: typeof asset.update;
export declare const assetUpdateBitasset: typeof asset.updateBitasset;
export declare const assetUpdateFeedProducers: typeof asset.updateFeedProducers;
export declare const assetIssue: typeof asset.issue;
export declare const assetReserve: typeof asset.reserve;
export declare const assetFundFeePool: typeof asset.fundFeePool;
export declare const assetPublishFeed: typeof asset.publishFeed;
export declare const proposalCreate: typeof proposal.create;
export declare const proposalUpdate: typeof proposal.update;
export declare const proposalDelete: typeof proposal.delete;
export declare const committeeMemberCreate: typeof committeeMember.create;
export declare const committeeMemberUpdate: typeof committeeMember.update;
export declare const committeeMemberUpdateGlobalParameters: typeof committeeMember.updateGlobalParameters;
export declare const vestingBalanceCreate: typeof vesting.balanceCreate;
export declare const vestingBalanceWithdraw: typeof vesting.balanceWithdraw;
export declare const balanceClaim: typeof balance.claim;
