import { transfer as transferOpProps, account, asset, proposal, committeeMember, vesting } from '../protocol';

export const transfer: typeof transferOpProps;
export const accountCreate: typeof account.create;
export const accountUpdate: typeof account.update;
export const accountWhitelist: typeof account.whitelist;
export const accountTransfer: typeof account.transfer;
export const assetCreate: typeof asset.create;
export const assetUpdate: typeof asset.update;
export const assetUpdateBitasset: typeof asset.updateBitasset;
export const assetUpdateFeedProducers: typeof asset.updateFeedProducers;
export const assetIssue: typeof asset.issue;
export const assetReserve: typeof asset.reserve;
export const assetFundFeePool: typeof asset.fundFeePool;
export const assetPublishFeed: typeof asset.publishFeed;
export const proposalCreate: typeof proposal.create;
export const proposalUpdate: typeof proposal.update;
export const proposalDelete: typeof proposal.delete;
export const committeeMemberCreate: typeof committeeMember.create;
export const committeeMemberUpdate: typeof committeeMember.update;
export const committeeMemberUpdateGlobalParameters: typeof committeeMember.updateGlobalParameters;
export const vestingBalanceCreate: typeof vesting.balanceCreate;
