export enum RESERVED_SPACE {
	RELATIVE_PROTOCOL = 0,
	PROTOCOL = 1,
	IMPLEMENTATION = 2,
}

export enum RELATIVE_PROTOCOL_OBJECT {
	// TODO:
}

export enum PROTOCOL_OBJECT {
	NULL = 0,
	BASE = 1,
	ACCOUNT = 2,
	ASSET = 3,
	FORCE_SETTLEMENT = 4,
	COMMITTEE_MEMBER = 5,
	WITNESS = 6,
	LIMIT_ORDER = 7,
	CALL_ORDER = 8,
	CUSTOM = 9,
	PROPOSAL = 10,
	OPERATION_HISTORY = 11,
	WITHDRAW_PERMISSION = 12,
	VESTING_BALANCE = 13,
	WORKER = 14,
	BALANCE = 15,
	CONTRACT = 16,
	CONTRACT_RESULT = 17,
}

export enum IMPLEMENTATION_OBJECT {
	GLOBAL_PROPERTY = 0,
	DYNAMIC_GLOBAL_PROPERTY = 1,
	INDEX_META = 2,
	ASSET_DYNAMIC_DATA = 3,
	ASSET_BITASSET_DATA = 4,
	ACCOUNT_BALANCE = 5,
	ACCOUNT_STATISTICS = 6,
	TRANSACTION = 7,
	BLOCK_SUMMARY = 8,
	ACCOUNT_TRANSACTION_HISTORY = 9,
	BLINDED_BALANCE = 10,
	CHAIN_PROPERTY = 11,
	WITNESS_SCHEDULE = 12,
	BUDGET_RECORD = 13,
}
