export declare enum RESERVED_SPACE_ID {
	RELATIVE_PROTOCOL = 0,
	PROTOCOL = 1,
	IMPLEMENTATION = 2,
}

export declare enum IMPLEMENTATION_OBJECT_TYPE_ID {
	GLOBAL_PROPERTY = 0,
	DYNAMIC_GLOBAL_PROPERTY = 1,
	ASSET_DYNAMIC_DATA = 2,
	ASSET_BITASSET_DATA = 3,
	ACCOUNT_BALANCE = 4,
	ACCOUNT_STATISTICS = 5,
	TRANSACTION_DEDUPE = 6,
	BLOCK_SUMMARY = 7,
	ACCOUNT_TRANSACTION_HISTORY = 8,
	CHAIN_PROPERTY = 9,
	SPECIAL_AUTHORITY = 10,
	CONTRACT_BALANCE = 11,
	CONTRACT_HISTORY = 12,
	CONTRACT_STATISTICS = 13,
	ACCOUNT_ADDRESS = 14,
	CONTRACT_POOL = 15,
	MALICIOUS_COMMITTEEMEN = 16,
	INCENTIVES_POOL = 17,
}

export declare enum VOTE_TYPE_ID {
	COMMITTEE = 0,
}
