declare enum PROTOCOL_OBJECT_TYPE_ID {
	NULL = 0,
	BASE = 1,
	ACCOUNT = 2,
	ASSET = 3,
	COMMITTEE_MEMBER = 4,
	PROPOSAL = 5,
	OPERATION_HISTORY = 6,
	VESTING_BALANCE = 7,
	BALANCE = 8,
	CONTRACT = 9,
	CONTRACT_RESULT = 10,
	BLOCK_RESULT = 11,
	ETH_ADDRESS = 12,
	SIDECHAIN_ETH_DEPOSIT = 13,
	SIDECHAIN_ETH_WITHDRAW = 14,
	ERC20_TOKEN = 15,
	SIDECHAIN_ERC20_DEPOSIT_TOKEN = 16,
	SIDECHAIN_ERC20_WITHDRAW_TOKEN = 17,
	OBJECT_TYPE_COUNT = 18,
}

export default PROTOCOL_OBJECT_TYPE_ID;
