import serializable from './serializable';
import { uint64, uint32 } from './basic-types';
import * as OperationsIds from '../constants/operations-ids';

const noFee = serializable({});
const defaultFee = serializable({ fee: uint64 });

const withPricePerKB = serializable({
	fee: uint64,
	price_per_kbyte: uint32,
});

export default {
	[OperationsIds.TRANSFER]: defaultFee,
	[OperationsIds.LIMIT_ORDER_CREATE]: defaultFee,
	[OperationsIds.LIMIT_ORDER_CANCEL]: defaultFee,
	[OperationsIds.CALL_ORDER_UPDATE]: defaultFee,
	[OperationsIds.FILL_ORDER]: noFee,
	[OperationsIds.ACCOUNT_CREATE]: serializable({
		basic_fee: uint64,
		premium_fee: uint64,
		price_per_kbyte: uint32,
	}),
	[OperationsIds.ACCOUNT_UPDATE]: withPricePerKB,
	[OperationsIds.ACCOUNT_WHITELIST]: defaultFee,
	[OperationsIds.ACCOUNT_UPGRADE]: serializable({
		membership_annual_fee: uint64,
		membership_lifetime_fee: uint64,
	}),
	[OperationsIds.ACCOUNT_TRANSFER]: defaultFee,
	[OperationsIds.ASSET_CREATE]: serializable({
		symbol3: uint64,
		symbol4: uint64,
		long_symbol: uint64,
		price_per_kbyte: uint32,
	}),
	[OperationsIds.ASSET_UPDATE]: withPricePerKB,
	[OperationsIds.ASSET_UPDATE_BITASSET]: defaultFee,
	[OperationsIds.ASSET_UPDATE_FEED_PRODUCERS]: defaultFee,
	[OperationsIds.ASSET_ISSUE]: withPricePerKB,
	[OperationsIds.ASSET_RESERVE]: defaultFee,
	[OperationsIds.ASSET_FUND_FEE_POOL]: defaultFee,
	[OperationsIds.ASSET_SETTLE]: defaultFee,
	[OperationsIds.ASSET_GLOBAL_SETTLE]: defaultFee,
	[OperationsIds.ASSET_PUBLISH_FEED]: defaultFee,
	[OperationsIds.PROPOSAL_CREATE]: withPricePerKB,
	[OperationsIds.PROPOSAL_UPDATE]: withPricePerKB,
	[OperationsIds.PROPOSAL_DELETE]: defaultFee,
	[OperationsIds.WITHDRAW_PERMISSION_CREATE]: defaultFee,
	[OperationsIds.WITHDRAW_PERMISSION_UPDATE]: defaultFee,
	[OperationsIds.WITHDRAW_PERMISSION_CLAIM]: defaultFee,
	[OperationsIds.WITHDRAW_PERMISSION_DELETE]: defaultFee,
	[OperationsIds.COMMITTEE_MEMBER_CREATE]: defaultFee,
	[OperationsIds.COMMITTEE_MEMBER_UPDATE]: defaultFee,
	[OperationsIds.COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS]: defaultFee,
	[OperationsIds.VESTING_BALANCE_CREATE]: defaultFee,
	[OperationsIds.VESTING_BALANCE_WITHDRAW]: defaultFee,
	[OperationsIds.CUSTOM]: withPricePerKB,
	[OperationsIds.ASSERT]: defaultFee,
	[OperationsIds.BALANCE_CLAIM]: noFee,
	[OperationsIds.OVERRIDE_TRANSFER]: defaultFee,
	[OperationsIds.ASSET_SETTLE_CANCEL]: noFee,
	[OperationsIds.ASSET_CLAIM_FEES]: defaultFee,
	[OperationsIds.BID_COLLATERAL]: defaultFee,
	[OperationsIds.EXECUTE_BID]: noFee,
	[OperationsIds.CREATE_CONTRACT]: defaultFee,
	[OperationsIds.CALL_CONTRACT]: defaultFee,
	[OperationsIds.CONTRACT_TRANSFER]: defaultFee,
	[OperationsIds.CHANGE_SIDECHAIN_CONFIG]: defaultFee,
	[OperationsIds.ACCOUNT_ADDRESS_CREATE]: withPricePerKB,
	[OperationsIds.TRANSFER_TO_ADDRESS]: defaultFee,
	[OperationsIds.GENERATE_ETH_ADDRESS]: defaultFee,
	[OperationsIds.CREATE_ETH_ADDRESS]: defaultFee,
	[OperationsIds.DEPOSIT_ETH]: defaultFee,
	[OperationsIds.WITHDRAW_ETH]: defaultFee,
	[OperationsIds.APPROVE_WITHDRAW_ETH]: defaultFee,
	[OperationsIds.CONTRACT_FUND_POOL]: defaultFee,
	[OperationsIds.CONTRACT_WHITELIST]: defaultFee,
	[OperationsIds.SIDECHAIN_ISSUE]: defaultFee,
	[OperationsIds.SIDECHAIN_BURN]: defaultFee,
	[OperationsIds.REGISTER_ERC20_TOKEN]: serializable({ fee: uint64, pool_fee: uint64 }),
	[OperationsIds.DEPOSIT_ERC20_TOKEN]: defaultFee,
	[OperationsIds.WITHDRAW_ERC20_TOKEN]: defaultFee,
	[OperationsIds.APPROVE_WITHDRAW_ETH]: defaultFee,
	[OperationsIds.CONTRACT_UPDATE]: defaultFee,
};
