import serializable from './serializable';
import { uint64, uint32 } from './basic-types';
import {
	TRANSFER,
	LIMIT_ORDER_CREATE,
	LIMIT_ORDER_CANCEL,
	CALL_ORDER_UPDATE,
	FILL_ORDER,
	ACCOUNT_CREATE,
	ACCOUNT_UPDATE,
	ACCOUNT_WHITELIST,
	ACCOUNT_UPGRADE,
	ACCOUNT_TRANSFER,
	ASSET_CREATE,
	ASSET_UPDATE,
	ASSET_UPDATE_BITASSET,
	ASSET_UPDATE_FEED_PRODUCERS,
	ASSET_ISSUE,
	ASSET_RESERVE,
	ASSET_FUND_FEE_POOL,
	ASSET_SETTLE,
	ASSET_GLOBAL_SETTLE,
	ASSET_PUBLISH_FEED,
	PROPOSAL_CREATE,
	PROPOSAL_UPDATE,
	PROPOSAL_DELETE,
	WITHDRAW_PERMISSION_CREATE,
	WITHDRAW_PERMISSION_UPDATE,
	WITHDRAW_PERMISSION_CLAIM,
	WITHDRAW_PERMISSION_DELETE,
	COMMITTEE_MEMBER_CREATE,
	COMMITTEE_MEMBER_UPDATE,
	COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS,
	VESTING_BALANCE_CREATE,
	VESTING_BALANCE_WITHDRAW,
	CUSTOM,
	ASSERT,
	BALANCE_CLAIM,
	OVERRIDE_TRANSFER,
	ASSET_SETTLE_CANCEL,
	ASSET_CLAIM_FEES,
	BID_COLLATERAL,
	EXECUTE_BID,
	CREATE_CONTRACT,
	CALL_CONTRACT,
	CONTRACT_TRANSFER,
} from '../constants/operations-ids';

const noFee = serializable({});
const defaultFee = serializable({ fee: uint64 });

const withPricePerKB = serializable({
	fee: uint64,
	price_per_kbyte: uint32,
});

export default {
	[TRANSFER]: defaultFee,
	[LIMIT_ORDER_CREATE]: defaultFee,
	[LIMIT_ORDER_CANCEL]: defaultFee,
	[CALL_ORDER_UPDATE]: defaultFee,
	[FILL_ORDER]: noFee,
	[ACCOUNT_CREATE]: serializable({
		basic_fee: uint64,
		premium_fee: uint64,
		price_per_kbyte: uint32,
	}),
	[ACCOUNT_UPDATE]: withPricePerKB,
	[ACCOUNT_WHITELIST]: defaultFee,
	[ACCOUNT_UPGRADE]: serializable({
		membership_annual_fee: uint64,
		membership_lifetime_fee: uint64,
	}),
	[ACCOUNT_TRANSFER]: defaultFee,
	[ASSET_CREATE]: serializable({
		symbol3: uint64,
		symbol4: uint64,
		long_symbol: uint64,
		price_per_kbyte: uint32,
	}),
	[ASSET_UPDATE]: withPricePerKB,
	[ASSET_UPDATE_BITASSET]: defaultFee,
	[ASSET_UPDATE_FEED_PRODUCERS]: defaultFee,
	[ASSET_ISSUE]: withPricePerKB,
	[ASSET_RESERVE]: defaultFee,
	[ASSET_FUND_FEE_POOL]: defaultFee,
	[ASSET_SETTLE]: defaultFee,
	[ASSET_GLOBAL_SETTLE]: defaultFee,
	[ASSET_PUBLISH_FEED]: defaultFee,
	[PROPOSAL_CREATE]: withPricePerKB,
	[PROPOSAL_UPDATE]: withPricePerKB,
	[PROPOSAL_DELETE]: defaultFee,
	[WITHDRAW_PERMISSION_CREATE]: defaultFee,
	[WITHDRAW_PERMISSION_UPDATE]: defaultFee,
	[WITHDRAW_PERMISSION_CLAIM]: defaultFee,
	[WITHDRAW_PERMISSION_DELETE]: defaultFee,
	[COMMITTEE_MEMBER_CREATE]: defaultFee,
	[COMMITTEE_MEMBER_UPDATE]: defaultFee,
	[COMMITTEE_MEMBER_UPDATE_GLOBAL_PARAMETERS]: defaultFee,
	[VESTING_BALANCE_CREATE]: defaultFee,
	[VESTING_BALANCE_WITHDRAW]: defaultFee,
	[CUSTOM]: withPricePerKB,
	[ASSERT]: defaultFee,
	[BALANCE_CLAIM]: noFee,
	[OVERRIDE_TRANSFER]: defaultFee,
	[ASSET_SETTLE_CANCEL]: noFee,
	[ASSET_CLAIM_FEES]: defaultFee,
	[BID_COLLATERAL]: defaultFee,
	[EXECUTE_BID]: noFee,
	[CREATE_CONTRACT]: defaultFee,
	[CALL_CONTRACT]: defaultFee,
	[CONTRACT_TRANSFER]: defaultFee,
};
